# Generated by Django 2.1.3 on 2019-12-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='titre',
            new_name='nom_matiere',
        ),
    ]
