# Generated by Django 2.1.3 on 2020-03-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='liste_classes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='specialite',
            name='liste_classes_id',
            field=models.TextField(default=''),
        ),
    ]
