# Generated by Django 2.1.3 on 2020-02-05 18:26

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(default='photos/profil.jpg', upload_to=mainapp.models.renommage_photo_eleve),
        ),
        migrations.AddField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo_url',
            field=models.CharField(max_length=300),
        ),
    ]
