# Generated by Django 2.1.3 on 2020-01-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typepayementdivers',
            name='date_deb',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='typepayementdivers',
            name='date_fin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='typepayementdivers',
            name='type_payement',
            field=models.CharField(default='Divers', max_length=100),
        ),
    ]
