# Generated by Django 2.1.3 on 2019-12-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='adminstaff',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='appellationapprenantformateur',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='appellationmodulechapitrelecon',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='appreciationnote',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='bus',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='cahierdetexte',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='chambre',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='classe',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='configannee',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='correpondancenotelettre',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='cours',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='coursinfosrecap',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='cycle',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='discipline',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='divisiontemps',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='document',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='dortoir',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='eleve',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='etab',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='groupe',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='groupeinfosrecap',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='jour',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='lesdivisiontemps',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='matiere',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='message',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='niveau',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='note',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='pause',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='payementadminstaff',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='payementeleve',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='periode',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='resultateleve',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='reunion',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='sousetab',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='typeadminstaff',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='typeenseignant',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='typepayementadminstaff',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='typepayementdivers',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='typepayementeleve',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='typereunion',
            name='archived',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
