# Generated by Django 2.1.4 on 2020-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='code_cours',
            field=models.CharField(default='Mathssss', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='volume_horaire_annuel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cours',
            name='volume_horaire_hebdo',
            field=models.IntegerField(default=1),
        ),
    ]
