# Generated by Django 2.1.3 on 2020-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('nom_eleve', models.CharField(max_length=100)),
                ('id_eleve', models.IntegerField()),
                ('matricule_eleve', models.CharField(max_length=20)),
                ('nom_bourse', models.CharField(max_length=100)),
                ('id_bourse', models.IntegerField()),
                ('nom_classe', models.CharField(max_length=100)),
                ('id_classe', models.IntegerField()),
                ('montant', models.FloatField()),
                ('archived', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='sousetab',
            name='nom_etab',
            field=models.CharField(max_length=100),
        ),
    ]
