# Generated by Django 2.1.4 on 2020-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200117_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='nom_cours',
            new_name='nom_matiere',
        ),
        migrations.AddField(
            model_name='cours',
            name='id_classe',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cours',
            name='id_cycle',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cours',
            name='id_etab',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cours',
            name='id_matiere',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cours',
            name='id_sousetab',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cours',
            name='nom_classe',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='nom_cycle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='nom_etab',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='nom_sousetab',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
