# Generated by Django 2.1.3 on 2019-12-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191216_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['nom_cycle']},
        ),
    ]
