# Generated by Django 2.1.3 on 2020-02-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200205_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
