# Generated by Django 2.1.3 on 2020-01-13 16:18

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200111_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('cumul_montant', models.FloatField(default=0.0)),
                ('date_deb_valide', models.CharField(default='', max_length=20)),
                ('date_fin_valide', models.CharField(default='', max_length=20)),
                ('id_eleve', models.IntegerField()),
                ('id_type_payement_cantine', models.IntegerField()),
                ('is_more_recent', models.BooleanField(default=True)),
                ('archived', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PayementChambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('cumul_montant', models.FloatField(default=0.0)),
                ('date_deb_valide', models.CharField(default='', max_length=20)),
                ('date_fin_valide', models.CharField(default='', max_length=20)),
                ('id_eleve', models.IntegerField()),
                ('id_chambre', models.IntegerField()),
                ('id_dortoir', models.IntegerField()),
                ('id_type_payement_dortoir', models.IntegerField()),
                ('is_more_recent', models.BooleanField(default=True)),
                ('archived', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PayementFacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.FloatField()),
                ('cumul_montant', models.FloatField(default=0.0)),
                ('date_payement', models.CharField(max_length=30)),
                ('date_deb_valide', models.CharField(default='', max_length=20)),
                ('date_fin_valide', models.CharField(default='', max_length=20)),
                ('id_type_facture', models.IntegerField()),
                ('is_more_recent', models.BooleanField(default=True)),
                ('archived', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('cumul_montant', models.FloatField(default=0.0)),
                ('date_deb_valide', models.CharField(default='', max_length=20)),
                ('date_fin_valide', models.CharField(default='', max_length=20)),
                ('id_eleve', models.IntegerField()),
                ('id_type_payement_transport', models.IntegerField()),
                ('is_more_recent', models.BooleanField(default=True)),
                ('archived', models.CharField(default='0', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='payements_cantine',
            field=djongo.models.fields.ArrayReferenceField(default='', on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='mainapp.Cantine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='payements_dortoir',
            field=djongo.models.fields.ArrayReferenceField(default='', on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='mainapp.PayementChambre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='payements_transport',
            field=djongo.models.fields.ArrayReferenceField(default='', on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='mainapp.Transport'),
            preserve_default=False,
        ),
    ]
