# Generated by Django 2.1.3 on 2019-12-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191226_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeApprenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('type_apprenant', models.CharField(max_length=200)),
                ('archived', models.CharField(default='0', max_length=2)),
                ('id_sousetab', models.IntegerField(default=1)),
                ('nom_sousetab', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
