# Generated by Django 2.1.3 on 2020-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200329_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialite',
            name='liste_classes_id',
        ),
        migrations.AddField(
            model_name='specialite',
            name='id_niveau',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='specialite',
            name='nom_niveau',
            field=models.CharField(default='', max_length=100),
        ),
    ]
