# Generated by Django 2.1.3 on 2020-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200329_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialite',
            name='id_niveau',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom_etab',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='nom_sousetab',
            field=models.CharField(default='', max_length=100),
        ),
    ]
