# Generated by Django 2.1.3 on 2019-12-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_typeapprenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeapprenant',
            old_name='type_apprenant',
            new_name='nom_type_apprenant',
        ),
    ]
