# Generated by Django 2.1.3 on 2020-02-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_eleve_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='adresse',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(max_length=30),
        ),
    ]
