# Generated by Django 2.1.3 on 2020-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201006_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisiontempscours',
            name='quota_notes',
            field=models.TextField(default=''),
        ),
    ]
