# Generated by Django 2.1.3 on 2019-12-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191226_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='id_sousetab',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discipline',
            name='nb_heures',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='discipline',
            name='nom_sousetab',
            field=models.CharField(default='', max_length=100),
        ),
    ]
