# Generated by Django 2.1.3 on 2020-03-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200329_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='liste_classes_afficher',
            field=models.TextField(default=''),
        ),
    ]
