# Generated by Django 2.1.3 on 2019-12-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191227_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='nb_heures',
            new_name='nb_heures_max',
        ),
        migrations.AddField(
            model_name='discipline',
            name='nb_heures_min',
            field=models.FloatField(default=0),
        ),
    ]
