# Generated by Django 2.1.3 on 2019-12-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20191227_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='sanction',
            field=models.TextField(default=''),
        ),
    ]
