# Generated by Django 2.1.3 on 2019-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_conditionrenvoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionSucces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField(default=0)),
                ('id_sousetab', models.IntegerField(default=1)),
                ('nom_sousetab', models.CharField(default='', max_length=100)),
                ('id_niveau', models.IntegerField(default=1)),
                ('nom_niveau', models.CharField(default='', max_length=100)),
                ('archived', models.CharField(default='0', max_length=2)),
            ],
        ),
    ]
